services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/hrmDashboardDB
      - RUST_LOG=info # Add logging
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: postgres:16.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hrmDashboardDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hrmDashboardDB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    # Removed ports:5432 to prevent external access (only web can access)

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
